# This is a basic workflow to help you get started with Actions
name: testcase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - uses: actions/checkout@v2

      - name: Run ${{ matrix.package }} tests
        run: cargo test -p ${{ matrix.package }}

    strategy:
      matrix:
        package:
          - dbc-price-ocw
          - online-committee
          - rent-machine
          - maintain-committee
          - committee
